services:
  web:
    image: nginx:latest
    container_name: blog-nginx
    volumes:
      - ./src/public:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - blog-network

  php:
    build: .
    container_name: blog-php
    volumes:
      - ./src:/var/www/html
      - ./logs:/var/log
      - ./wait-for-it.sh:/wait-for-it.sh
    networks:
      - blog-network
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    depends_on:
      - db
    command: >
      sh -c "/wait-for-it.sh db:3306 --timeout=30 --strict -- php /var/www/html/init/init-admin.php && php-fpm"
      
  db:
    image: mysql:5.7
    container_name: blog-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql-init/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "3306:3306"
    networks:
      - blog-network

volumes:
  db-data:

networks:
  blog-network:
