name: Run PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Change to the /src directory
      run: cd src

    - name: Install Composer dependencies
      working-directory: src
      run: composer install

    - name: Set PHPUnit as executable
      working-directory: src
      run: chmod +x vendor/bin/phpunit  # This will set the required executable permissions for PHPUnit

    - name: Run PHPUnit
      working-directory: src
      run: vendor/bin/phpunit --testdox
